name: Ventana a la Biodiversidad
favicon: null
layout_spectrum: 0.03755
typography_spectrum: 0.2395305351819843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f2cc'
    - '#3c303a'
    - '#9d808c'
    - '#74a6bd'
    - '#0f66c1'
  brandStrength: 0.4375
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
